AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for cross-account support access from Taimos'
Resources:
  SupportRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: TaimosSupport
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::292004443359:user/hoegertn'
            Condition:
              Bool:
                'aws:MultiFactorAuthPresent': 'true'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowRemoteAdminAccess
                Effect: Allow
                Action: '*'
                Resource: '*'

Outputs:
  RoleName:
    Description: 'The name of the support role'
    Value: !Ref SupportRole
  AccountId:
    Description: 'The id of the AWS account'
    Value: !Ref 'AWS::AccountId'